### PR TITLE
Add European Remote to the Newsletters section

### PR DESCRIPTION
**Pull request by imaginalis**
- Fix alphabetical order in newsletters
- Add European Remote with description

[European Remote - newsletter](https://europeanremote.com)

This allows you to subscribe to the selected remote opportunities available for European folks.
The jobs are curated by the tech stack and sent weekly. We're getting them outside of the major hiring platforms, which gives a unique variety of options available. 

All in all, we're focused on the product companies only, but when it comes to scale both VC-backed companies and bootstrapped ones are included.

### CODE REVIEW

**Comment by imaginalis** [comment]
Hey @RichardLitt , why closed?

**Comment by RichardLitt** [comment]
Thank you.

**Comment by imaginalis** [comment]
Thanks much @RichardLitt

**Review by ismukier — COMMENTED** [review]
Thank you so much for arranging it alphabetically. Really appreciate your effort! 🤍 That’s great 👏

**Pull request merged**
