### PR TITLE
Git commit show conference added

### PR DESCRIPTION
**Pull request by gitcommitshow**
gitcommit.show

A completely online 2-day conference for developers 
This is a good resource for developers to Lear and network remotely

### CODE REVIEW

**Comment by RichardLitt** [comment]
Cool! Thanks.

**Comment by RichardLitt** [comment]
@gitcommitshow Please remove your modal that pops up, asking for emails, when you close the tab. That's really annoying.

**Comment by gitcommitshow** [comment]
> @gitcommitshow Please remove your modal that pops up, asking for emails, when you close the tab. That's really annoying.

Thanks for the feedback. Will do it as soon as I get back to my system.

**Comment by gitcommitshow** [comment]
@RichardLitt done. Popup removed. Thanks for bringing it to the notice

**Comment by RichardLitt** [comment]
@gitcommitshow That's awesome. Well done, and thank you!

**Pull request merged**
