### PR TITLE
Added to Tools - Communication

### PR DESCRIPTION
**Pull request by azizsaya**
Added "Tips for immersive video calls" to Tools - Communication

### CODE REVIEW

**Comment by RichardLitt** [comment]
This is actually pretty awesome. But it's not alphabetized?

**Review by azizsaya — COMMENTED** [review]
Added to Tools - Communication (#677), alphabetized now

**Comment by azizsaya** [comment]
Ah! didn't notice that corrected now.

**Comment by RichardLitt** [comment]
Ta

**Pull request merged**
