### PR TITLE
Add karat.io/practice to #interviewing

### PR DESCRIPTION
**Pull request by bhollan**
Karat is trying to change the field of software engineering interviewing, both for candidates and companies.  They offer free practice interviews to candidates who sign up.  Karat staffs professional interviewers do perform interviews for clients (interviewing-as-a-service) and they do practice interviews for free.

### CODE REVIEW

**Comment by bhollan** [comment]
I have no idea why this failed.  Let me know what needs to be changed and I'll fix it.

**Comment by RichardLitt** [comment]
Thanks. That sounds like a paywall to me.

**Comment by bhollan** [comment]
Karat provides this service completely free of charge. You have to sign up which does not require a credit card at all.  Just name/email/etc.  This is not a paywall.

Can I get this re-opened, or should I re-submit?  This is not a paywall and is a wonderful service that Karat provides out of their own pocket.

**Comment by RichardLitt** [comment]
Thanks for the explanation. Merged!

**Pull request merged**
