### PR TITLE
Add Geckoboard to the companies list

### PR DESCRIPTION
**Pull request by chubbypanda**

### CODE REVIEW

**Comment by reclaimer** [comment]
The job listing there isn't remote-friendly. Is it? :/

**Comment by chubbypanda** [comment]
I interviewed there 2 weeks ago for a remote position (Support Engineer).

**Comment by chubbypanda** [comment]
Apparently the positions was already filled. I'm attaching the screenshot I took at that time. Also, it's still visible at https://remoteok.io/remote-jobs/19426-remote-support-engineer-geckoboard

geckoboard_support-engineer

**Comment by lukasz-madon** [comment]
It's not a company with "Remote DNA"

**Pull request closed without merging**
