### PR TITLE
Add kaamwork

### PR DESCRIPTION
**Pull request by vishalkdotcom**
[kaamwork](https://kaam.work/)

kaamwork provides remote job opportunities globally.
Hiring across Engineering, Data Science roles.
Complete online process for hiring, interviews.

### CODE REVIEW

**Comment by vishalkdotcom** [comment]
@RichardLitt I just wanted to bring this to your notice that the Builds are failing due to some of the previous dead links. This PR adds a new and working link only.

Here is the snapshot of the build errors:
image

https://travis-ci.org/github/lukasz-madon/awesome-remote-job/builds/684529004

I manually checked, the links mentioned in the build snapshot are really dead.


Please let me know, if I should raise a new PR to add kaamwork or any additional step required.
Thanks!

**Comment by RichardLitt** [comment]
Thanks, @vishalkdotcom. I turned down this PR not because of the build, but because you didn't read [the Contributing guidelines](https://github.com/lukasz-madon/awesome-remote-job/blob/master/CONTRIBUTING.md). Please do so, and let me know if this should be reopened, and why. Thanks. :)

**Comment by vishalkdotcom** [comment]
Thanks. I read it, but I guess I missed something. I'll read it again and see if I can open it again. 😊

**Comment by RichardLitt** [comment]
Haha. Thanks for understanding. Look at point 1. Why is Kaamwork different than the other Job Boards on here? What makes it more awesome than what we have?

**Pull request closed without merging**
