### PR TITLE
Add Remote First to job board list

### PR DESCRIPTION
**Pull request by gravyboat**
As a disclaimer I own and run this site, just want to be transparent about it (even with the note in the contributing guide).

### CODE REVIEW

**Comment by gravyboat** [comment]
@lukasz-madon Is anything missing to get this merged in? If it's not acceptable to get merged I'll close it out.

**Comment by gravyboat** [comment]
@lukasz-madon Sorry to bug you about this again, but I would either like to get this merged in or close this PR.

**Comment by lukasz-madon** [comment]
There are no job.

**Comment by gravyboat** [comment]
At this time that's correct because the site is relatively new. It's a job board that customers can post their jobs on, it is not an aggregator.

**Pull request closed without merging**
