### PR TITLE
Fix typo, add Paylocity to remote DNA list

### PR DESCRIPTION
**Pull request by colin-higgins**

### CODE REVIEW

**Comment by zeke** [comment]
Technolgoy!

**Comment by lukasz-madon** [comment]
can you fix the merge conflict please?

**Comment by ScionSoftware** [comment]
I don't have write access to resolve the merge. I could submit a new pull request? It should only be taking the Paylocity line and dropping it to the bottom.

**Comment by ScionSoftware** [comment]
Pulled merged fixed

**Pull request merged**
