### PR TITLE
Add Relocation Incentives section

### PR DESCRIPTION
**Pull request by Courtny**
**[Insert URL you're adding here]**
https://tulsaremote.com/

**[Explain what this URL adds and why it is awesome]**
Tulsa Remote offers money upfront to help with relocation expenses, a monthly stipend to keep things moving and the rest when you've finished the first year.

### CODE REVIEW

**Comment by Courtny** [comment]
Not sure why travis is failing, doesn't appear to be related to my update but maybe it it?

**Comment by RichardLitt** [comment]
This reminds me of [Vermont's own initiative to do this](https://legislature.vermont.gov/assets/Documents/2018/Docs/BILLS/S-0094/S-0094%20As%20Passed%20by%20Both%20House%20and%20Senate%20Unofficial.pdf). Can we create an "Remote working incentive schemes" section?

**Comment by RichardLitt** [comment]
The travis failure is unrelated. Don't worry about it.

**Comment by Courtny** [comment]
@RichardLitt I like the idea of adding in a new section, if you think it will become pretty common! I know that I have heard of similar things happening in European countries as well.

**Comment by RichardLitt** [comment]
I think it will. Estonia has similar stuff. 

Go ahead and add one where you think is fit. :)

**Comment by RichardLitt** [comment]
Love it. Thank you!

**Pull request merged**
