### PR TITLE
Add housing livinitnomad.com

### PR DESCRIPTION
**Pull request by livinitnomad**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Can you re-add when you are open? Looks like that's not happening until October.

**Comment by livinitnomad** [comment]
Well, the whole point of putting it up now is so people can see it and book their place. If I post it in October then it will be too late for people to book...

**Comment by RichardLitt** [comment]
I get the idea. But this is not an ad board; it's a list of existing, awesome things. Right now, your page is just a page, and I have no idea how it will look in October. 

BTW: I've been to the Azores, and they're awesome, and it's probably a great place a coliving thing. Good idea. I'm interested in seeing how you do. 

Reopen when you launch. Thanks for understanding.

**Comment by livinitnomad** [comment]
No problem RIchard, thank you.

**Pull request closed without merging**
