### PR TITLE
Add company premoted.com

### PR DESCRIPTION
**Pull request by jaredreich**
Add company premoted.com to job boards

### CODE REVIEW

**Comment by RichardLitt** [comment]
@jaredreich Many of these job postings are not remote, and you have to read their descriptions to find that out. I think this site is selling itself as a remote job posting site without doing the leg work of ensuring that is the case. I'm going to vote no on this one. Feel free to let me know if I should look again. Thanks.

**Comment by jaredreich** [comment]
Actually, every single post was hand-crafted and guaranteed 100% remote as the sources came from the top remote posting sites (weworkremotely, stackoverflow remote).

I'm glad you closed for now though since the site is a side project that's currently not being updated. I have future plans to make it much better and automate everything via RSS feeds so that it's constantly up-to-date and aggregating all the best remote sources.

I'll request to re-look into adding this in once that time comes. Thanks for looking.

**Comment by RichardLitt** [comment]
> Actually, every single post was hand-crafted and guaranteed 100% remote as the sources came from the top remote posting sites (weworkremotely, stackoverflow remote).

I hear you. But this is not what I saw on the site. For instance, ["dog friendly office"](https://premoted.com/job/426/crowdspring-frontend-engineer-react), ["relocation help (to their offices in barcelona and Malta)"](https://premoted.com/job/413/casumo-javascript-developer), ["partially remote"](https://premoted.com/job/416/syrinx-consulting-senior-javascript-developer-reactjs). 

Good luck finding time to bring it back up. I would suggest a bit more hand-editing before calling it a remote site.

**Comment by jaredreich** [comment]
Right, good points. But again, the posts were directly pulled from job postings from sources that are already listed on this awesome-remote-job list. So for premoted.com being denied but weworkremotely.com and stackoverflow remote being accepted is opposing logic. Either way, you can re-assess later. Cheers!

**Comment by RichardLitt** [comment]
Hmm. You're right that they also have non-remote jobs. They don't label themselves as remote job sites, though. 

Again, good luck finding time! I really hope you succeed, not trying to be hard here. :)

**Pull request closed without merging**
