### PR TITLE
added vollna.com

### PR DESCRIPTION
**Pull request by hebrianvasyl**
An aggregator tool based on machine learning, that focus only on quality freelance projects.
Also, it has awesome analytical data about the freelance market.

URL: https://www.vollna.com/

### CODE REVIEW

**Comment by hebrianvasyl** [comment]
Hi, @RichardLitt 

Is it closed because of the link to the landing page, not for jobs list page?
Or another reason?

**Comment by RichardLitt** [comment]
Hey hey. I closed this because it wasn't clear to me why it was different from any other job boards, and because your GitHub account didn't show a long history of open source. I couldn't tell if you're interested in GitHub as a marketing platform, or not, which makes your submission a bit iffy to me. Feel free to write more about why you think this board needs inclusion, and take a look at the Contributing guide. Thanks. :)

**Comment by hebrianvasyl** [comment]
Hi, @RichardLitt 
Thank you for the reply, I understand your doubts and respect your opinion.

This is my project, so yes, it seems like it's marketing.
But I truly hope my site could be useful for freelancers because it is a great tool. Also storing a ton of analytical data about the freelance market.
It different than other job boards, because it focused on freelance sites. If someone working on Upwork or Freelancer (or both at the same time), he (or she) don't interested in full-time remote jobs. But wants to see interesting freelance projects, filtered by skills and requirements.

If you are interested in history, I work as a freelancer since 2011, and in 2014 I create a tool for myself. 2 years later I made it public, and other freelancers liked the tool and they started using it.  Most of the people from Eastern Europe. Already 3500 active users.
People free to use analytical data to create articles and researches, and a few popular Ukraine and Russian sites use it.
Then I decided to upgrade the site, design and created the second version of the tool. If you are interested, the old version is primelance.com

And I understand, if you decide not to add this site :)

Have a nice day!

**Comment by RichardLitt** [comment]
Thanks for explaining. Best of luck.

**Pull request merged**
