### PR TITLE
add usefedora.com to list

### PR DESCRIPTION
**Pull request by cjroth**

### CODE REVIEW

**Comment by bzz** [comment]
How can one find a remote job opportunities in there?

**Comment by cjroth** [comment]
Updated it to take you to the careers page.

**Comment by lukasz-madon** [comment]
I'd be great if you have a line saying that you work remotely.

**Comment by cjroth** [comment]
Fair enough. It's not exclusively remote, but some of our peeps are remote some of the time. Oh well.

**Pull request closed without merging**
