### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by carperez**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Want to add a note that most of these are in German?

**Comment by carperez** [comment]
It's not always the case but maybe I could add a note: 
[Freelancermap](https://www.freelancermap.com/remote-jobs) - Freelance & contract jobs for IT experts *Many German projects

 Could you please let me know how to add this note? It's my first commit. Thanks!

**Comment by RichardLitt** [comment]
That sounds good to me! [Here is a guide on amending your commit](https://github.com/RichardLitt/knowledge/blob/master/github/amending-a-commit-guide.md). If you find it too hard, let me know, and I can do it myself and merge it.

**Comment by carperez** [comment]
Would you mind to do that for me? To be honest, I don't know where to start and I would like to avoid doing something that I shouldn't do! I really appreciate it!

**Comment by RichardLitt** [comment]
If that guide doesn't help, I should change it! :D I would do a few more GitHub introduction courses; this is something you'll be asked to do in the future. :) 

I'll just merge this now. But there's no way you could mess up anything important - the worst is just time spent learning what to do. :) 

Good luck in the future. Thanks for the addition. Merging this because of the scope of the ads, and of the German content, which we don't have a lot of.

**Comment by carperez** [comment]
Thanks Richard! I think the guide is great - it was just me! I'm definitely reading more and maybe jumping into a few videos as well as I think this might help.

**Pull request merged**
