### PR TITLE
Adding Remote Works podcast

### PR DESCRIPTION
**Pull request by jdsharp**
Adding Remote Works podcast

### CODE REVIEW

**Comment by RichardLitt** [comment]
It's a bit early! Can you wait until you have 5-10 podcasts? I can't judge the quality with only two. :)

**Comment by jdsharp** [comment]
Hey, that totally makes sense. For future contributors, it might be helpful to add notes about what your expectations are on this to the contributions guidelines ;)

**Comment by RichardLitt** [comment]
@jdsharp How does #336 look?

**Comment by jdsharp** [comment]
@RichardLitt looks good (added one comment to the PR)

**Comment by RichardLitt** [comment]
Thank you!

**Pull request closed without merging**
