### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by motivapp**
Added a newsletter of Remote jobs @ tech startups

### CODE REVIEW

**Comment by tedder** [comment]
@lukasz-madon note this doesn't.. actually.. exist. The subscription is for launch notification/landing page, right out of the Reis playbook. (not that that's a bad thing, but this isn't actually a Thing yet)

**Comment by lukasz-madon** [comment]
Not good enough.

**Comment by motivapp** [comment]
Hey @lukasz-madon can you provide some feedback on why it is not good enough?

We feature the best remote jobs ($100k+/yr) for designers, developers and writers packed in a newsletter.... How can it get any better?! :smiley_cat: 


@tedder Thanks for the feedback. We are launching on February 1st and already have the first newsletters ready to go out!!

**Comment by lukasz-madon** [comment]
List is for high quality stuff. I cannot judge the quality if it doesn't exist yet.

**Comment by motivapp** [comment]
@lukasz-madon I definitely agree with you and appreciate you keeping this list high quality.

Here is a sample newsletter of the Engineer Daily Jobs email: http://jobscri.be/sample

We will be officially launching in a few days and I will reach out to you then!

Thanks in advance.

**Pull request closed without merging**
