### PR TITLE
Added JS Remotely job board

### PR DESCRIPTION
**Pull request by IvanJov**
The new remote job board just for JS jobs

### CODE REVIEW

**Comment by RichardLitt** [comment]
An about page would be nice. Who runs this? Where is stuff scraped from?

**Comment by IvanJov** [comment]
I am the owner of the project and I released it yesterday. It's scrapping data from bunch of sites, like we work remotely, stack-overflow, authentic jobs, github jobs.. and I am going to add more. I've developed a mechanism that filters just remote JS jobs and so far it's looking good. Had a bunch new things to add, like tags, search.. and I am talking with remote companies to post their jobs on the site.

Let me know if you want to know anything else!

**Comment by RichardLitt** [comment]
Cool. Thank you. Take a look at the Contributing: 

 > Feel free to post your own company or site. However, make sure there is content before posting - we can't tell whether something is awesome if there is little to see. For a good reference, there should be at least six months of content.

I'm not sure this qualifies at the moment. Right now, it is just a list, and nothing more. Thank you for submitting, however.  Feel free to reopen when you have more features.

**Comment by IvanJov** [comment]
Sure, I am going to work on this and reopen in couple months! Thanks!

**Comment by RichardLitt** [comment]
Thanks for understanding! Best of luck, really. :)

**Pull request closed without merging**
