### PR TITLE
Added descriptions, removed redirects and corrected typos

### PR DESCRIPTION
**Pull request by sgelob**
Added more descriptions to lists, converted unordered lists to ordered, corrected and unified texts, added new video and removed some domain redirect (Ex. http://nomadjobs.io/ –> https://remoteok.io/).

### CODE REVIEW

**Comment by lukasz-madon** [comment]
:+1: can you fix merge conflicts ?

**Comment by lukasz-madon** [comment]
@sgelob

**Comment by RichardLitt** [comment]
@sgelob Hey! Thanks again. Sorry for the super long delay. Will merge if rebased soon - otherwise, going to close and reimplement these changes.

**Comment by RichardLitt** [comment]
Nevermind. Merged in 8809fbcd7491668c921250fb9db609982d936871. Thank you!

**Pull request closed without merging**
