### PR TITLE
Added: Gittask

### PR DESCRIPTION
**Pull request by MatthewMueller**
Brand new marketplace for coding tasks that pays back the open source community. Featured on:

- [Product Hunt](http://www.producthunt.com/posts/gittask) Top 10 products on Friday January 16th
- [Codrops Collective #151](tympanus.net/codrops/collective/collective-151/) Weekly front-end newsletter

### CODE REVIEW

**Comment by lukasz-madon** [comment]
Hmm It's not a job board

Further discussion https://news.ycombinator.com/item?id=8825308

**Comment by MatthewMueller** [comment]
@lukasz-madon Yep, I think Gittask is well-aligned with the goal of this repository though. From the website itself:

> We built gittask to help people quickly earn money during the hours of their choosing, from a location of their choosing. Tasks are specific to libraries and languages, so it's easy to find the perfect match for your skill set and start earning money quickly.

While the tasks are often shorter, you can still earn plenty of money working remotely. It's similar to TaskRabbit or Lyft in this way. Would a different section be more suitable?

**Comment by tedder** [comment]
It seems like a section for "moonlighting"/contractual work is a decent idea. OTOH gittask is only available after registering and it appears there's no RSS feed or saved search email.

**Comment by MatthewMueller** [comment]
@tedder we're working on it :smile:

**Comment by lukasz-madon** [comment]
Sectopm Remote Moonlighting is a good idea

**Comment by MatthewMueller** [comment]
Sounds good! I've added the remote moonlighting section :-D

**Pull request merged**
