### PR TITLE
README Tidy Up

### PR DESCRIPTION
**Pull request by SethiPandi**
This is just a small tidy up on for things in the README.

* There were many HTTP links which had HTTPS available. (Most redirected anyway, but some required manually going to HTTPS.)
* There were 2 pages which I removed entirely, as they appear to redirect to other pages, I could not find the original content again. They could technically be re-added with a Web Archive link instead:
  * https://web.archive.org/web/20200414233835/https://conferences.oreilly.com/oscon/oscon2014/public/schedule/detail/34260
  * https://web.archive.org/web/20200414234422/https://www.virgin.com/richard-branson/one-day-offices-will-be-a-thing-of-the-past
* Fixed a few typos, namely case-sensitive ones such as `Javascript` vs `JavaScript` or `Github` vs `GitHub` and word hyphenation, for example `medium sized` vs [`medium-sized`](https://www.merriam-webster.com/dictionary/medium-sized).
* Some pages had redirects, as the company changed name, or they work under another company. One has been removed because it redirected to a domain that was already on the list, and another was renamed to the new name.
* Fixed broken Markdown link. (There was a space between ] and ( so it didn't get formatted correctly.)

This PR does _not_ add any new resources, it should only be changing the existing resources.

High hopes everything should still be fine? ^-^' Please let me know if there're any problems.

--- 

Nice repo by the way, found this alongside https://github.com/remoteintech/remote-jobs.
Really nice to have so much information on companies with remote DNA collated this way.

### CODE REVIEW

**Comment by SethiPandi** [comment]
Of the issues reported by Travis:

```
Issues :-(
> Links 
  1. [L146] 503 https://europeremotely.com/  
  2. [L187]  https://www.weloveangular.com/ getaddrinfo: Temporary failure in name resolution 
  3. [L202]  https://remotephp.io getaddrinfo: Name or service not known 
  4. [L204]  https://www.remotelyawesomejobs.com/ Connection timed out - connect(2) for "www.remotelyawesomejobs.com" port 443 
  5. [L500] 404 https://softwareengineering.stackexchange.com/questions/tagged/home?sort=votes  
  6. [L507]  https://weworkremotely.ro/ getaddrinfo: Name or service not known 
```

[1] Is currently down for maintenance.
[5] StackExchange reports a 404 when the search query has no results.

[2, 3, 4, 6] This PR does not touch those websites, they appear to be dead links?

**Comment by RichardLitt** [comment]
Feel free to remove the links with travis issues, and then we can merge this? Great work!

**Comment by SethiPandi** [comment]
> Feel free to remove the links with travis issues, and then we can merge this? Great work! 

@RichardLitt Can I just verify, would you like **all 6** removed?

**Comment by RichardLitt** [comment]
I've had a "remove first, if it's great, someone will re-add it" policy I've used for the last few years. Seems to apply here, too. Go ahead and remove all six.

**Comment by SethiPandi** [comment]
Well, that's slightly inconvenient. :thinking: 

`https://stackoverflow.com/jobs/companies?q=&l=&r=true` is failing.

StackOverflow broke this page since my last commit it seems. XD ^-^'
https://stackoverflow.com/jobs/companies

**Comment by RichardLitt** [comment]
Just keep that one in. If it breaks, people know where to find StackOverflow.

**Comment by RichardLitt** [comment]
Thank you.

**Pull request merged**
