### PR TITLE
Add LivingSocial

### PR DESCRIPTION
**Pull request by danrabinowitz**

### CODE REVIEW

**Comment by lukasz-madon** [comment]
>There are currently no results which match your search criteria.

**Comment by danrabinowitz** [comment]
Strange, it worked for me. Oh well, I updated the PR with a more generic link for the LivingSocial careers page.

**Comment by lukasz-madon** [comment]
There are merge conflicts. Cloud you fix it according to https://github.com/lukasz-madon/awesome-remote-job/blob/master/CONTRIBUTING.md (sort + description)

**Comment by danrabinowitz** [comment]
Fixed. Thank you. :smile:

**Pull request merged**
