### PR TITLE
Migrate page to Jekyll site on master branch

### PR DESCRIPTION
**Pull request by SourcingDenis**

### CODE REVIEW

**Comment by RichardLitt** [comment]
I'm... not quite sure what you were trying to do here. Mostly because I wasn't aware we had a GitHub Pages site at all. 

@lukasz-madon Was there a plan for that?

**Comment by SourcingDenis** [comment]
@RichardLitt @lukasz-madon Sorry guys. I am a non-programmer and just walking around and trying all the things. So it probably happened accidentally rather than in narrative form. Thanks for your understanding and have a good one! 🙌

**Comment by RichardLitt** [comment]
No worries!

**Comment by RichardLitt** [comment]
@lukasz-madon Mind if we just delete `gh-pages`?

**Comment by lukasz-madon** [comment]
yeah, sure

**Comment by RichardLitt** [comment]
Done! Thanks, @SourcingDenis, for pointing this out!

**Pull request closed without merging**
