### PR TITLE
Added remote job boards.

### PR DESCRIPTION
**Pull request by angelnikolov**
Hey, first of all - nice list of resources! Pretty useful! I added two remote job boards to the mix.

https://remotefrontendjobs.com and https://remotebackendjobs.com

The domain names are pretty self-explanatory but still - both sites aggregate the top 22 remote job boards in the world and provide hand-curated, categorized and cleaned-up jobs in the two categories (frontend and backend).

### CODE REVIEW

**Comment by angelnikolov** [comment]
@lukasz-madon Is this PR ine?

**Comment by Technetium1** [comment]
I wish I could see who owned those?

**Comment by angelnikolov** [comment]
@Technetium1 What do you mean by those?

**Comment by Technetium1** [comment]
> @Technetium1 What do you mean by those?

I mean that it seems they are mirror images of each other but with only back to front and front into back... Even the Twitter is mirrored. Even going that deep I cannot find the owner.

**Comment by angelnikolov** [comment]
@Technetium1 I am the owner :) Yes, you are correct, both sites are absolutely the same. They source data from the same database and use the same services. The only difference is the type of jobs they show.

**Comment by Technetium1** [comment]
In that case I have no concerns about it 😁

Good work

**Comment by lukasz-madon** [comment]
added

**Pull request closed without merging**
