### PR TITLE
Add http://remoteparttimejobs.com

### PR DESCRIPTION
**Pull request by tomekw**

### CODE REVIEW

**Comment by waldyrious** [comment]
For reference, this PR was closed because it doesn't follow the [contribution guidelines](https://github.com/lukasz-madon/awesome-remote-job/blob/master/CONTRIBUTING.md):

> Feel free to post your own company or site. However, make sure there is content before posting - we can't tell whether something is awesome if there is little to see. For a good reference, there should be at least six months of content.

**Comment by RichardLitt** [comment]
Thanks @waldyrious. I was a bit tired this morning and didn't feel like explaining it again. :P

**Comment by waldyrious** [comment]
No problem :+1:, I figured as much. Maintainer burnout is a real thing and I apologize for not doing my part since @lukasz-madon took the smart step to spread those responsibilities among multiple people. (I keep telling myself I need to get involved in less projects...)

**Comment by waldyrious** [comment]
By the way, since this seems to be a common response to contributions to this repo, perhaps it would be useful to setup a reply template (e.g. something similar to what I wrote above). Unfortunately GitHub doesn't allow these to be defined per-project, so you'd have to do it in [your own account settings](https://github.com/settings/replies).

**Comment by RichardLitt** [comment]
> By the way, since this seems to be a common response to contributions to this repo, perhaps it would be useful to setup a reply template (e.g. something similar to what I wrote above). 

We could just use an issue template in this repo. What do you think?

**Comment by waldyrious** [comment]
A PR template is the appropriate option, I assume that's what you mean. We recently created one over at tldr-pages/tldr#1434. It looks like in this case, we could simply convert the contribution guidelines to a checklist in the PR template, but I'm afraid that would be excessively long and onerous. We could probably trim the list down to at most 10 entries. Does that seem doable to you?

**Comment by tomekw** [comment]
I'm really sorry guys for being such pain in the ass :(

**Comment by waldyrious** [comment]
@tomekw you weren't. The fact that @RichardLitt was tired of replying the same thing to multiple contributors clearly shows that the project is failing to make its requirements sufficiently clear to prospective contributors. If anything, you helped by triggering the discussion on how to improve the situation :)

**Comment by RichardLitt** [comment]
What @waldyrious. No worries, @tomekw. Good luck with the site!

**Comment by tomekw** [comment]
Thank you! Keep it up!

**Pull request closed without merging**
