### PR TITLE
Add a comic: Why working from home is both awesome and horrible

### PR DESCRIPTION
**Pull request by greatghoul**
This resource is from my list [remote-working](https://github.com/greatghoul/remote-working). my list only accepts resources in Chinese now, so I want to move this nice comic into your **awesome** list.

Please help. Thank you.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Ahahah I love it. Yes, this works. Thanks. Have you linked your list, too?

**Comment by greatghoul** [comment]
@RichardLitt No, I haven't. I don't know if it's nice to link a Chinese-ONLY list to an international one, It may not make sense for your readers.

**Comment by RichardLitt** [comment]
You'd be surprised. It may be that people are here and more fluent in Chinese than in English, and they may enjoy your list, as well. I know I would, if I knew Chinese.

**Comment by greatghoul** [comment]
Oh, maybe through my list, companies out of China will know there are many excellent people who are experienced in working remotely, these companies may hire from China.

Please add my list into yours, I will create a pull request.

**Pull request merged**
