### PR TITLE
Add new resource [Adeva - An exclusive developers network]

### PR DESCRIPTION
**Pull request by TsTrv**
http://adevait.com

Adeva is an exclusive developers network. The vision of the company is the bring equal opportunity to developers no matter their location, race, and color.

### CODE REVIEW

**Comment by RichardLitt** [comment]
> no matter their location, race, and color.

But... exclusive? Why is that?

**Comment by TsTrv** [comment]
It is exclusive because every individual should pass a thorough screening process before joining the network.

**Comment by RichardLitt** [comment]
Cool. Is Adeva itself remote?

**Comment by TsTrv** [comment]
Yes, it is.

**Comment by RichardLitt** [comment]
Sweet. Thanks!

**Pull request merged**
