### PR TITLE
add Simple to companies

### PR DESCRIPTION
**Pull request by gorsuch**
/cc @whilp

### CODE REVIEW

**Comment by whilp** [comment]
<3

**Comment by chovy** [comment]
simple.com allows for remote?

**Comment by whilp** [comment]
Sure does -- I started remote back in 2012. About 30% of our engineers are remote at this point. See "Anywhere, US" in eg the ops posting:

http://banksimple.theresumator.com/apply/1SvlR6/Operations-Engineer.html

**Comment by vmbrasseur** [comment]
@chovy Yes, we do. Not only are [we're hiring](https://www.simple.com/careers), but we're darn swell people. :heart:

**Comment by whilp** [comment]
HAI VICKY

**Comment by vmbrasseur** [comment]
HAIL WHILP

(k, gonna stop replying on a closed PR now :-) )

**Comment by chovy** [comment]
@vmbrasseur i looked at jobs page, no need for FE.

**Comment by jedisct1** [comment]
"Unfortunately, we can not support international applicants at this time" :(

**Comment by whilp** [comment]
@jedisct1 yeah, that's sadly true -- believe me, though, we're working on it. ;)

**Pull request merged**
